parameters:

    environment.application.defaults:

        # Packaged App environment defaults here
        # To be modified by the app developer only
        # To override these parameters for your running application, see /data/environment.yml
        
        INITIALIZATION_MODE: TRUE
        DATABASE_URL: sqlite://%kernel.root_dir%/../data/database.db?absolute