security:
    encoders:
        Netgusto\HelloBundle\Entity\AppUser:
            algorithm: sha512
            encode_as_base64: false
            iterations: 1024

    providers:
        appuser:
            entity: { class: Netgusto\HelloBundle\Entity\AppUser, property: email }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            anonymous: ~
